#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package install mtr <args...>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  which mtr >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -y mtr
  fi

  log::success "install mtr success."
}

run() {
  core $@
}

run $@
